##############################################################
#
# This file includes all the test targets as well as all the
# non-default build rules and test recipes.
#
##############################################################

###### Additional includes that are specific to this directory ######

# Placeholder for additional include files.


##############################################################
#
# Test targets
#
##############################################################

###### Place all generic definitions here ######

# This defines tests which run tools of the same name.  This is simply for convenience to avoid
# defining the test name twice (once in TOOL_ROOTS and again in TEST_ROOTS).
# Tests defined here should not be defined in TOOL_ROOTS and TEST_ROOTS.
TEST_TOOL_ROOTS := 

# This defines the tests to be run that were not already defined in TEST_TOOL_ROOTS.
TEST_ROOTS := test_mini test_mini_v2 test_granularity test_taint_binop_r2r test_taint_binop_m2r test_taint_binop_r2m test_taint_xfer_r2r test_taint_xfer_m2r test_taint_xfer_r2m test_taint_xfer_pushpop test_taint_xfer_stos test_taint_xfer_movbe test_taint_xfer_movlph test_taint_xfer_lea

# This defines the tools which will be run during the the tests, and were not already defined in
# TEST_TOOL_ROOTS.
TOOL_ROOTS := track track_v2 nullpin libdft libdft-dta instrace taint_tracer

# This defines the static analysis tools which will be run during the the tests. They should not
# be defined in TEST_TOOL_ROOTS. If a test with the same name exists, it should be defined in
# TEST_ROOTS.
# Note: Static analysis tools are in fact executables linked with the Pin Static Analysis Library.
# This library provides a subset of the Pin APIs which allows the tool to perform static analysis
# of an application or dll. Pin itself is not used when this tool runs.
SA_TOOL_ROOTS :=

# This defines all the applications that will be run during the tests.
APP_ROOTS := mini_test mini_test_v2 granularity_test

# This defines any additional object files that need to be compiled.
OBJECT_ROOTS := 

# This defines any additional dlls (shared objects), other than the pintools, that need to be compiled.
DLL_ROOTS :=

# This defines any static libraries (archives), that need to be built.
LIB_ROOTS := 

###### Place architecture-specific definitions here ######

# Place ia32-specific definitions here if they apply to all supported operating systems.
ifeq ($(TARGET),ia32)
    TOOL_CXXFLAGS += -m32 -Wno-deprecated-declarations
    LIBDFT_INC_PATH	= $(realpath ../src32/)
    LIBDFT_PATH	= $(realpath ../src32/obj-ia32/)
endif

# Place intel64-specific definitions here if they apply to all supported operating systems.
ifeq ($(TARGET),intel64)
	TOOL_CXXFLAGS += -Wno-deprecated-declarations
    LIBDFT_INC_PATH	= $(realpath ../src/)
    LIBDFT_PATH	= $(realpath ../src/obj-intel64/)
endif

##############################################################
#
# Test recipes
#
##############################################################

###### Finalize sanity here ######

# This section contains recipes for tests other than the default.
# See makefile.default.rules for the default test rules.
# All tests in this section should adhere to the naming convention: <testname>.test


##############################################################
#
# Build rules
#
##############################################################

# This section contains the build rules for all binaries that have special build rules.
# See makefile.default.rules for the default build rules.

###### Special tools' build rules ######

LOGGING_FLAGS = -DNO_PINTOOL_LOG
TOOL_CXXFLAGS += $(LOGGING_FLAGS) -I$(LIBDFT_INC_PATH) -L$(LIBDFT_PATH)
TOOL_LIBS += -L$(LIBDFT_PATH) -ldft

INPUT_FILE=cur_input

TEST_DIR := test
TEST_OBJDIR := $(TEST_DIR)/obj-$(TARGET)/
TEST_BINS := taint_binop_r2r_smoke taint_binop_m2r_smoke taint_binop_r2m_smoke taint_xfer_r2r_smoke taint_xfer_m2r_smoke taint_xfer_r2m_smoke taint_xfer_pushpop_smoke taint_xfer_stos_smoke taint_xfer_movbe_smoke taint_xfer_movlph_smoke taint_xfer_lea_smoke
TEST_BINARIES := $(addprefix $(TEST_OBJDIR),$(addsuffix $(EXE_SUFFIX),$(TEST_BINS)))

# Custom build rule for mini_test with debug symbols and no optimization
$(OBJDIR)mini_test$(EXE_SUFFIX): mini_test.cpp
test_mini: $(OBJDIR)/track$(PINTOOL_SUFFIX) ${OBJDIR}/mini_test$(EXE_SUFFIX)
	$(PIN) -t $< -- $(OBJDIR)mini_test$(EXE_SUFFIX)  ${INPUT_FILE}

test_mini_v2: $(OBJDIR)/track_v2$(PINTOOL_SUFFIX) ${OBJDIR}/mini_test_v2$(EXE_SUFFIX)
	$(PIN) -t $< -- $(OBJDIR)mini_test_v2$(EXE_SUFFIX) ${INPUT_FILE}

test_granularity: $(OBJDIR)/track$(PINTOOL_SUFFIX) ${OBJDIR}/granularity_test$(EXE_SUFFIX)
	$(PIN) -t $< -- $(OBJDIR)granularity_test$(EXE_SUFFIX)

test_bins: $(TEST_BINARIES)

$(TEST_OBJDIR):
	mkdir -p $@

$(TEST_OBJDIR)%$(EXE_SUFFIX): $(TEST_DIR)/%.c | $(TEST_OBJDIR)
	$(CC) $(APP_CFLAGS) -g -gcolumn-info -O0 -fno-omit-frame-pointer -fno-pie -no-pie -o $@ $<

test_taint_binop_r2r: $(OBJDIR)/taint_tracer$(PINTOOL_SUFFIX) $(TEST_OBJDIR)taint_binop_r2r_smoke$(EXE_SUFFIX)
	$(PIN) -t $< -- $(TEST_OBJDIR)taint_binop_r2r_smoke$(EXE_SUFFIX)

test_taint_binop_m2r: $(OBJDIR)/taint_tracer$(PINTOOL_SUFFIX) $(TEST_OBJDIR)taint_binop_m2r_smoke$(EXE_SUFFIX)
	$(PIN) -t $< -- $(TEST_OBJDIR)taint_binop_m2r_smoke$(EXE_SUFFIX)

test_taint_binop_r2m: $(OBJDIR)/taint_tracer$(PINTOOL_SUFFIX) $(TEST_OBJDIR)taint_binop_r2m_smoke$(EXE_SUFFIX)
	$(PIN) -t $< -- $(TEST_OBJDIR)taint_binop_r2m_smoke$(EXE_SUFFIX)

test_taint_xfer_r2r: $(OBJDIR)/taint_tracer$(PINTOOL_SUFFIX) $(TEST_OBJDIR)taint_xfer_r2r_smoke$(EXE_SUFFIX)
	$(PIN) -t $< -- $(TEST_OBJDIR)taint_xfer_r2r_smoke$(EXE_SUFFIX)

test_taint_xfer_m2r: $(OBJDIR)/taint_tracer$(PINTOOL_SUFFIX) $(TEST_OBJDIR)taint_xfer_m2r_smoke$(EXE_SUFFIX)
	$(PIN) -t $< -- $(TEST_OBJDIR)taint_xfer_m2r_smoke$(EXE_SUFFIX)

test_taint_xfer_r2m: $(OBJDIR)/taint_tracer$(PINTOOL_SUFFIX) $(TEST_OBJDIR)taint_xfer_r2m_smoke$(EXE_SUFFIX)
	$(PIN) -t $< -- $(TEST_OBJDIR)taint_xfer_r2m_smoke$(EXE_SUFFIX)

test_taint_xfer_pushpop: $(OBJDIR)/taint_tracer$(PINTOOL_SUFFIX) $(TEST_OBJDIR)taint_xfer_pushpop_smoke$(EXE_SUFFIX)
	$(PIN) -t $< -- $(TEST_OBJDIR)taint_xfer_pushpop_smoke$(EXE_SUFFIX)

test_taint_xfer_stos: $(OBJDIR)/taint_tracer$(PINTOOL_SUFFIX) $(TEST_OBJDIR)taint_xfer_stos_smoke$(EXE_SUFFIX)
	$(PIN) -t $< -- $(TEST_OBJDIR)taint_xfer_stos_smoke$(EXE_SUFFIX)

test_taint_xfer_movbe: $(OBJDIR)/taint_tracer$(PINTOOL_SUFFIX) $(TEST_OBJDIR)taint_xfer_movbe_smoke$(EXE_SUFFIX)
	$(PIN) -t $< -- $(TEST_OBJDIR)taint_xfer_movbe_smoke$(EXE_SUFFIX)

test_taint_xfer_movlph: $(OBJDIR)/taint_tracer$(PINTOOL_SUFFIX) $(TEST_OBJDIR)taint_xfer_movlph_smoke$(EXE_SUFFIX)
	$(PIN) -t $< -- $(TEST_OBJDIR)taint_xfer_movlph_smoke$(EXE_SUFFIX)

test_taint_xfer_lea: $(OBJDIR)/taint_tracer$(PINTOOL_SUFFIX) $(TEST_OBJDIR)taint_xfer_lea_smoke$(EXE_SUFFIX)
	$(PIN) -t $< -- $(TEST_OBJDIR)taint_xfer_lea_smoke$(EXE_SUFFIX)

check_taint_binops: test_bins $(OBJDIR)/taint_tracer$(PINTOOL_SUFFIX)
	$(TEST_DIR)/check_taint_binops.sh "$(PIN)" "$(OBJDIR)/taint_tracer$(PINTOOL_SUFFIX)" "$(TEST_OBJDIR)"

check_taint_xfer: test_bins $(OBJDIR)/taint_tracer$(PINTOOL_SUFFIX)
	$(TEST_DIR)/check_taint_xfer.sh "$(PIN)" "$(OBJDIR)/taint_tracer$(PINTOOL_SUFFIX)" "$(TEST_OBJDIR)"

clean: clean-tests

clean-tests:
	rm -rf $(TEST_OBJDIR) taint_trace_*.txt
